zeyneplervesarp/swe574-javagang

frontend/src/api/register.js, frontend/src/views/CreateService.vue, frontend/src/views/Register.vue
=> users can add new tags

backend/src/main/java/com/swe573/socialhub/dto/ServiceDto.java, backend/src/main/java/com/swe573/socialhub/service/ServiceService.java, backend/src/main/java/com/swe573/socialhub/service/UserServiceApprovalService.java, backend/src/main/resources/application.properties, backend/src/test/java/com/swe573/socialhub/ServiceServiceUnitTests.java
=> added participant user list dto

frontend/src/views/SingleService.vue
=> added participant list to ui

frontend/src/views/Notifications.vue
=> added url to notifications

backend/src/main/java/com/swe573/socialhub/service/UserService.java, backend/src/test/java/com/swe573/socialhub/UserServiceUnitTests.java
=> registered users are added userType & added tests

backend/src/main/java/com/swe573/socialhub/config/LoadDatabase.java
We will need to resolve LoadDatabase conflicts.
=> 46 add dummy data for flagging

backend/src/main/java/com/swe573/socialhub/controller/ServiceController.java, backend/src/main/java/com/swe573/socialhub/service/ServiceService.java, backend/src/test/java/com/swe573/socialhub/ServiceServiceUnitTests.java
=> converted save service method to upsert

backend/src/main/java/com/swe573/socialhub/config/LoadDatabase.java, backend/src/main/java/com/swe573/socialhub/domain/Event.java, backend/src/main/java/com/swe573/socialhub/domain/LoginAttempt.java, backend/src/main/java/com/swe573/socialhub/domain/Service.java, backend/src/main/java/com/swe573/socialhub/domain/UserEventApproval.java, backend/src/main/java/com/swe573/socialhub/domain/UserServiceApproval.java, backend/src/main/java/com/swe573/socialhub/enums/FeedEvent.java, backend/src/main/java/com/swe573/socialhub/enums/LoginAttemptType.java, backend/src/main/java/com/swe573/socialhub/repository/LoginAttemptRepository.java, backend/src/main/java/com/swe573/socialhub/service/UserService.java
All login attempts, successful or unsuccessful, is persisted.
=> Login attempt

frontend/src/views/CreateService.vue, frontend/src/views/Register.vue, frontend/src/views/SingleService.vue
=> 97 create new tag doesnt work

frontend/src/views/SingleService.vue
=> removed ack notification after service rate

frontend/src/views/UserPage.vue
added rating summary to user profile page
=> added rating summary to user profile page

backend/src/main/java/com/swe573/socialhub/config/LoadDatabase.java, backend/src/main/java/com/swe573/socialhub/controller/StatsController.java, backend/src/main/java/com/swe573/socialhub/domain/User.java, backend/src/main/java/com/swe573/socialhub/dto/StatContainerDto.java, backend/src/main/java/com/swe573/socialhub/dto/StatsDto.java, backend/src/main/java/com/swe573/socialhub/repository/ServiceRepository.java, backend/src/main/java/com/swe573/socialhub/repository/UserRepository.java, backend/src/main/java/com/swe573/socialhub/repository/UserServiceApprovalRepository.java, backend/src/main/java/com/swe573/socialhub/repository/activitystreams/ApprovedQueryableServiceApprovalRepository.java, backend/src/main/java/com/swe573/socialhub/repository/activitystreams/DateCountableRepository.java, backend/src/main/java/com/swe573/socialhub/service/StatsService.java, frontend/package-lock.json, frontend/package.json, frontend/src/api/register.js, frontend/src/views/AdminServices.vue
=> Stats impl

frontend/src/views/UserPage.vue
should be merged together with [this](https://github.com/zeyneplervesarp/swe574-javagang/pull/153)
=> added delete user button to user detail page

backend/src/main/java/com/swe573/socialhub/config/SecurityConfiguration.java
=> added featured services to unauthorized paths

backend/src/main/java/com/swe573/socialhub/config/LoadDatabase.java, backend/src/test/java/com/swe573/socialhub/UserServiceTests.java
=> Badge impl

backend/pom.xml, backend/src/main/java/com/swe573/socialhub/config/LoadDatabase.java, backend/src/main/java/com/swe573/socialhub/service/TagService.java
As part of #182 
Our mock database now picks from a list of cities to create mock services and users, instead of getting random coordinates.
=> choose between cities

frontend/src/views/AdminUsers.vue
=> fix layout and sorting

backend/src/main/java/com/swe573/socialhub/config/LoadDatabase.java, backend/src/main/java/com/swe573/socialhub/controller/ServiceController.java, backend/src/main/java/com/swe573/socialhub/controller/StatsController.java, backend/src/main/java/com/swe573/socialhub/controller/UserController.java, backend/src/main/java/com/swe573/socialhub/domain/Service.java, backend/src/main/java/com/swe573/socialhub/domain/User.java, backend/src/main/java/com/swe573/socialhub/domain/UserServiceApproval.java, backend/src/main/java/com/swe573/socialhub/dto/DailyStatsDto.java, backend/src/main/java/com/swe573/socialhub/dto/PaginatedListResponse.java, backend/src/main/java/com/swe573/socialhub/dto/PaginatedResponse.java, backend/src/main/java/com/swe573/socialhub/service/StatsService.java, frontend/package-lock.json, frontend/package.json, frontend/src/api/register.js, frontend/src/views/AdminStats.vue
Added daily stats endpoint to services.
Added pretty charts in Admin Statistics page in frontend.
Addresses #213
=> Daily stats

backend/src/main/java/com/swe573/socialhub/config/LoadDatabase.java, frontend/src/views/AdminServices.vue
Added better demo examples as part of #182
=> Services page fix

backend/src/main/java/com/swe573/socialhub/config/LoadDatabase.java
Popularly requested changes to load database :)
Fixes #236 and #204
=> Load database fixes

frontend/src/views/AdminUsers.vue, frontend/src/views/UserPage.vue, frontend/src/views/components/Services.vue
closes #246 
closes #250
closes #209
=> Bug/minor UI fixes ece

frontend/src/views/AdminFeed.vue, frontend/src/views/AdminFlaggedServices.vue, frontend/src/views/AdminFlaggedUsers.vue, frontend/src/views/SingleService.vue, frontend/src/views/components/Services.vue
closes https://github.com/zeyneplervesarp/swe574-javagang/issues/254
closes  https://github.com/zeyneplervesarp/swe574-javagang/issues/253
closes https://github.com/zeyneplervesarp/swe574-javagang/issues/251
=> Bug/minor UI fixes

backend/src/main/java/com/swe573/socialhub/config/LoadDatabase.java, backend/src/test/java/com/swe573/socialhub/ActivityStreamServiceTests.java, backend/src/test/java/com/swe573/socialhub/ServiceServiceUnitTests.java
Fixes #269 
Added checks to prevent random seed from exceeding current time. Also fixes two broken test cases.
=> Future events fix

backend/src/main/java/com/swe573/socialhub/controller/ServiceController.java, backend/src/main/java/com/swe573/socialhub/service/ServiceService.java, frontend/src/api/register.js, frontend/src/views/Search.vue, frontend/src/views/components/Services.vue
Search by location is moved to All Services
=> Search by location is moved to All Services
